spring:
    h2:
      console:
          enabled: true
          path: /h2
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:~/templatedb
      username: sa
      password:
    jpa:
      hibernate:
          ddl-auto: update
server:
    error:
      include-message: always
    port: 8081